name = "maxingkingvfx"
main = "vite.config.js"
compatibility_date = "2025-04-11"

[build]
command = "npm run build"

[build.upload]
target = "dist"

[pages]
build_command = "npm run build"
build_output_directory = "dist"

[site]
bucket = "dist"
entry-point = "index.html"
