name = "maxingkingvfx"

[build]
command = "npm run build"

[build.output]
directory = "dist"

[env.production]
[env.production.build]
command = "npm run build"

[env.production.build.output]
directory = "dist"

[env.github]
[env.github.build]
command = "npm run build"

[env.github.build.output]
directory = "dist"

[env.cloudflare]
[env.cloudflare.build]
command = "npm run build"

[env.cloudflare.build.output]
directory = "dist"

[env.cloudflare.branch]
name = "main"
