name = "maxingkingvfx"
main = "./index.html"

[build]
command = "npm run build"

[build.output]
directory = "dist"

# Add environment variables for different deployments
[env.production]
[env.production.build]
command = "npm run build"

[env.github]
[env.github.build]
command = "npm run build"

[env.github.build.output]
directory = "dist"

[env.cloudflare]
[env.cloudflare.build]
command = "npm run build"

[env.cloudflare.build.output]
directory = "dist"
